package com.futureforge.ai.service;

import com.futureforge.ai.entity.User;
import com.futureforge.ai.entity.UserProfile;
import com.futureforge.ai.repository.UserRepository;
import com.futureforge.ai.repository.UserProfileRepository;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.properties.TextAlignment;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class PdfExportService {

    private final UserRepository userRepository;
    private final UserProfileRepository userProfileRepository;

    public byte[] generateCareerReport() {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        Optional<UserProfile> profileOpt = userProfileRepository.findByUserId(user.getId());

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(baos);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);

        // Header
        Paragraph header = new Paragraph("FutureForge AI - Career Report")
                .setTextAlignment(TextAlignment.CENTER)
                .setBold()
                .setFontSize(24);
        document.add(header);

        document.add(new Paragraph("\n"));

        // User Info
        document.add(new Paragraph("Name: " + user.getFullName()).setBold());
        document.add(new Paragraph("Email: " + user.getEmail()));
        
        if (profileOpt.isPresent()) {
            UserProfile p = profileOpt.get();
            document.add(new Paragraph("Target Role: " + (p.getCareerGoal() != null ? p.getCareerGoal() : "N/A")));
            document.add(new Paragraph("Skills: " + (p.getSkillsJson() != null ? p.getSkillsJson() : "None listed")));
        }

        document.add(new Paragraph("\n--- AI Analysis Summary ---").setBold());
        document.add(new Paragraph("Your profile indicates a strong foundation. Continue following your generated roadmap to bridge any skill gaps. Keep up the great work in your domain!"));

        document.add(new Paragraph("\n--- Active Roadmap Milestones ---").setBold());
        document.add(new Paragraph("Check your dashboard for the detailed interactive roadmap milestones and track your progress in real-time."));

        document.add(new Paragraph("\nGenerated by FutureForge AI on " + java.time.LocalDate.now())
                .setTextAlignment(TextAlignment.RIGHT)
                .setItalic()
                .setFontSize(10));

        document.close();
        return baos.toByteArray();
    }
}
